crest_ns/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("", include("main.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [

	path("", views.IndexView, name="index"),
	path("auction/", views.AuctionView, name="auction"),
	path("discount/", views.DiscountView, name="discount"),
	path("discount/finish/<str:domain_name>/", views.Discount2View, name="discount2"),
	path("all_discount/", views.AllDiscountView, name="all_discount"),
	path("account/", views.AccountView, name="account"),
	path("checkout/", views.CheckOutView, name="checkout"),

	path("find/", views.FindView, name="find"),
	path("result/<str:domain_name>/", views.ResultView, name="result"),
	path("buy/<str:domain_name>/", views.BuyView, name="buy"),
	path("finish/", views.FinishView, name="finish"),
	path("registered/", views.RegisteredView, name="registered"),
	path("manage/<str:domain_name>/", views.ManageView, name="manage"),
	path("docs/", views.DocsView, name="docs"),
	
	path("transfer/", views.Transfer1View, name="transfer1"),
	path("transfer/<str:domain_name>/<str:domain_namek>/finish/", views.Transfer2View, name="transfer2"),
	path("transfer/finish/", views.Transfer3View, name="transfer3"),
	
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Discount(models.Model):
    txn_hash = models.TextField(default="none")
    name = models.TextField(default="none")
    wallet = models.TextField(default="none")
    age = models.TextField(default="none")
    
    status = models.BooleanField(default=False)
    
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name




class Domain(models.Model):
    token_id = models.TextField(default="none")
    name = models.TextField(default="none")
    age = models.TextField(default="none")
    address = models.TextField(default="none")
    first_address = models.TextField(default="none")
    description = models.TextField(default="none")
    image = models.TextField(default="none")
    
    status = models.BooleanField(default=True)
    
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.address

main/templates/main/base2.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/2.jpg' %}">
    <!-- Page title -->
    <title>Core Naming Service | Crest Protocol</title>
    
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'assets/images/2.jpg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Crest Protocol, Metaverse, ENS, EVM, Ethereum, Name Service, Domain Names, Core Chain, NFTs, Humanizes Identities, NFT Market, AibraLabs, Young Parrot, Core Token, Ethereum Name Service, ERC721, Testnet"/>

    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta property="og:title" content="Core Naming Service"/>
    <meta name="twitter:title" content="Core Naming Service"/>
    <meta name="twitter:image:width" content="400" />
    <meta name="twitter:image:height" content="300" />
    <meta name="twitter:image:src" content="{% static 'assets/images/2.jpg' %}" >

    <meta name="twitter:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>
    <meta property="og:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>

    
    <meta name="description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse." content="IE=edge"/>

    <title>Core Naming Service | Crest Protocol</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/2.jpg' %}"/>
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta property="og:title" content="Crest Protocol"/>
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <title>Core Naming Service | Crest Protocol</title>
<link rel="icon" href="{% static 'assets/images/2.jpg' %}" >
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<link rel="stylesheet" href="{% static 'assets/css/all.css' %}">

<link rel="stylesheet" href="{% static 'assets/font/flaticon.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap-icons.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/swiper.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/price-range-ui.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
</head>
<body>

<div class="preloader">
<div class="sk-cube-grid">
<div class="sk-cube sk-cube1"></div>
<div class="sk-cube sk-cube2"></div>
<div class="sk-cube sk-cube3"></div>
<div class="sk-cube sk-cube4"></div>
<div class="sk-cube sk-cube5"></div>
<div class="sk-cube sk-cube6"></div>
<div class="sk-cube sk-cube7"></div>
<div class="sk-cube sk-cube8"></div>
<div class="sk-cube sk-cube9"></div>
</div>
</div>


<a href="#" id="scroll-top" class="back-to-top-btn"><i class="fas fa-chevron-up"></i></a>


<header>

<nav>
<div class="header-menu-area">
<div class="container">
<div class="row">
<div class="col-xl-2 col-lg-2 col-sm-6 col-6">
<div class="logo text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
</div>
<div class="col-xl-7 col-lg-7 col-sm-6 col-6">
<a href="javascript:void(0)" class="hidden-lg hamburger">
<span class="h-top"></span>
<span class="h-middle"></span>
<span class="h-bottom"></span>
</a>
<nav class="main-nav">
<div class="logo mobile-ham-logo d-lg-none d-block text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
<ul>
<li class="">
<a href="/" class="active">Home</a>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Explore</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
<li><a href="{% url 'main:registered' %}">Registered Names</a></li>

</ul>
</li>
<li class="has-child-menu">
<a href="{% url 'main:docs' %}">Documentation</a>


</li>
</ul>
<div class="menu-search-wrap d-block d-lg-none">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search Here">
</form>
</div>
</nav>
</div>
<div class="col-xl-3 col-lg-3 d-none d-lg-block">
<div class="menu-search-wrap">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="domain_name" placeholder="Search Here">
</form>

</div>
</div>
</div>
</div>
</div>
</nav>

{% block content %}

{% endblock %}

<div class="footer-area design-1">
<div class="container">
<div class="row">
<div class="col-xl-12 col-lg-12 col-sm-12 col-12">
<div class="footer-wrap">
<div class="row justify-content-between">
<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
<div class="single-widget">
<div class="footer-logo">
<a href="/"><img width="30%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
<p>A decentralized domain naming service on core dao chain that allows users to easily discover and access decentralized services and applications.</p>
<div class="footer-social">
<ul>
<li><a href="https://twitter.com/crestprotocol_?s=21&t=1PmJM7PYRu2e096byownIA" target="_blank"><i class="fab fa-twitter"></i></a></li>
<li><a target="_blank" href="https://discord.gg/cyEuvRJF"><i class="fab fa-discord"></i></a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Usefull Links</h4>
</div>
<div class="footer-link">
<ul>

<li><a target="_blank" href="https://shadowswap.xyz/swap?outputCurrency=0xcFE4C0783d103C44f403Bb287d29af0bAE5D4E84">Buy</a></li>
<li><a href="{% url 'main:registered' %}">Registered Names</a></li>


</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Community</h4>
</div>
<div class="footer-link">
<ul>
<li><a target="_blank" href="https://discord.gg/cyEuvRJF">Help Center</a></li>
<li><a target="_blank" href="https://crestprotocol.co/files/Crest-Protocol-Whitepaper.pdf">Whitepaper</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Info</h4>
</div>
<div class="footer-link">
<ul>
<li><a href="{% url 'main:docs' %}">Documentation</a></li>

<li><a target="_blank" href="https://crestprotocol.co/">Crest Protocol</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
<div class="copy-right-area text-center">
<p class="copy-text">© 2023 CrestProtocol, All Rights Reserved.</p>
</div>
</div>
</div>
</div>
</div>


<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>

<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>

<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

<script src="{% static 'assets/js/slick.min.js' %}"></script>

<script src="{% static 'assets/js/swiper.js' %}"></script>

<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>

<script src="{% static 'assets/js/wow.min.js' %}"></script>

<script src="{% static 'assets/js/price-range-ui.js' %}"></script>

<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/counter-potnt.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>

<style>

        .btn {
          border: none;
          color: white;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
        }
        
        .enableEthereumButton {
          background-color: #037dd6;
        }
        .sendEthButton {
          background-color: #4CAF50;
        }
        
        </style>
        
        <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
        <script src="https://unpkg.com/web3@latest/dist/web3.min.js"></script>
        <script src="{% static 'js/index2.js' %}"></script>
        <script>
                    function forceLower(strInput)
                    {
                        strInput.value = strInput.value.toLowerCase();
                    }
                </script>
</body>


</html>

main/templates/main/base3.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/2.jpg' %}">
    <!-- Page title -->
    <title>Core Naming Service | Crest Protocol</title>
    
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'assets/images/2.jpg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="Crest Protocol, Metaverse, ENS, EVM, Ethereum, Name Service, Domain Names, Core Chain, NFTs, Humanizes Identities, NFT Market, AibraLabs, Young Parrot, Core Token, Ethereum Name Service, ERC721, Testnet"/>

    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta property="og:title" content="Core Naming Service"/>
    <meta name="twitter:title" content="Core Naming Service"/>
    <meta name="twitter:image:width" content="400" />
    <meta name="twitter:image:height" content="300" />
    <meta name="twitter:image:src" content="{% static 'assets/images/2.jpg' %}" >

    <meta name="twitter:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>
    <meta property="og:description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse."/>

    
    <meta name="description" content="Official Naming Service for Core Chain, A Humanized ID for the Metaverse." content="IE=edge"/>

    <title>Core Naming Service | Crest Protocol</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/images/2.jpg' %}"/>
    
    <link rel="alternate icon" href="{% static 'assets/images/2.jpg' %}">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <meta name="msapplication-TileColor" content="#da532c"/>
    <meta property="og:title" content="Crest Protocol"/>
    <link rel="icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'assets/images/2.jpg' %}" type="image/x-icon">
    <title>Core Naming Service | Crest Protocol</title>
<link rel="icon" href="{% static 'assets/images/2.jpg' %}" >
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

<link rel="stylesheet" href="{% static 'assets/css/all.css' %}">

<link rel="stylesheet" href="{% static 'assets/font/flaticon.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap-icons.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/swiper.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/price-range-ui.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
</head>
<body>

<div class="preloader">
<div class="sk-cube-grid">
<div class="sk-cube sk-cube1"></div>
<div class="sk-cube sk-cube2"></div>
<div class="sk-cube sk-cube3"></div>
<div class="sk-cube sk-cube4"></div>
<div class="sk-cube sk-cube5"></div>
<div class="sk-cube sk-cube6"></div>
<div class="sk-cube sk-cube7"></div>
<div class="sk-cube sk-cube8"></div>
<div class="sk-cube sk-cube9"></div>
</div>
</div>


<a href="#" id="scroll-top" class="back-to-top-btn"><i class="fas fa-chevron-up"></i></a>


<header>

<nav>
<div class="header-menu-area">
<div class="container">
<div class="row">
<div class="col-xl-2 col-lg-2 col-sm-6 col-6">
<div class="logo text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
</div>
<div class="col-xl-7 col-lg-7 col-sm-6 col-6">
<a href="javascript:void(0)" class="hidden-lg hamburger">
<span class="h-top"></span>
<span class="h-middle"></span>
<span class="h-bottom"></span>
</a>
<nav class="main-nav">
<div class="logo mobile-ham-logo d-lg-none d-block text-left">
<a href="/"><img width="60%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
</div>
<ul>
<li class="">
<a href="/" class="active">Home</a>
</li>
<li class="has-child-menu">
<a href="javascript:void(0)">Explore</a>
<i class="fl flaticon-plus">+</i>
<ul class="sub-menu">
<li><a href="{% url 'main:registered' %}">Registered Names</a></li>


</ul>
</li>
<li class="has-child-menu">
<a href="{% url 'main:docs' %}">Documentation</a>


</li>
</ul>
<div class="menu-search-wrap d-block d-lg-none">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="address" placeholder="Enter Address">
</form>
</div>
</nav>
</div>
<div class="col-xl-3 col-lg-3 d-none d-lg-block">
<div class="menu-search-wrap">
<form action="" class="menu-form" method="post">
  {% csrf_token %}
<a type="submit"><i class='bx bx-search'></i></a>
<input type="text" onkeyup="return forceLower(this);" name="address" placeholder="Enter Address">
</form>

</div>
</div>
</div>
</div>
</div>
</nav>

{% block content %}

{% endblock %}

<div class="footer-area design-1">
<div class="container">
<div class="row">
<div class="col-xl-12 col-lg-12 col-sm-12 col-12">
<div class="footer-wrap">
<div class="row justify-content-between">
<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
<div class="single-widget">
<div class="footer-logo">
<a href="/"><img width="30%" src="{% static 'assets/images/crest001.png' %}" alt=""></a>
<p>A decentralized domain naming service on core dao chain that allows users to easily discover and access decentralized services and applications.</p>
<div class="footer-social">
<ul>
<li><a href="https://twitter.com/crestprotocol_?s=21&t=1PmJM7PYRu2e096byownIA" target="_blank"><i class="fab fa-twitter"></i></a></li>
<li><a target="_blank" href="https://discord.gg/cyEuvRJF"><i class="fab fa-discord"></i></a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Usefull Links</h4>
</div>
<div class="footer-link">
<ul>

<li><a target="_blank" href="https://shadowswap.xyz/swap?outputCurrency=0xcFE4C0783d103C44f403Bb287d29af0bAE5D4E84">Buy</a></li>
<li><a href="{% url 'main:registered' %}">Registered Names</a></li>


</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Community</h4>
</div>
<div class="footer-link">
<ul>
<li><a target="_blank" href="https://discord.gg/cyEuvRJF">Help Center</a></li>
<li><a target="_blank" href="https://crestprotocol.co/files/Crest-Protocol-Whitepaper.pdf">Whitepaper</a></li>
</ul>
</div>
</div>
</div>
<div class="col-xl-2 col-lg-2 col-md-6 col-sm-6 col-6">
<div class="single-widget">
<div class="footer-title">
<h4>Info</h4>
</div>
<div class="footer-link">
<ul>
<li><a href="{% url 'main:docs' %}">Documentation</a></li>

<li><a target="_blank" href="https://crestprotocol.co/">Crest Protocol</a></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
<div class="copy-right-area text-center">
<p class="copy-text">© 2023 CrestProtocol, All Rights Reserved.</p>
</div>
</div>
</div>
</div>
</div>

<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>

<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>

<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

<script src="{% static 'assets/js/slick.min.js' %}"></script>

<script src="{% static 'assets/js/swiper.js' %}"></script>

<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>

<script src="{% static 'assets/js/wow.min.js' %}"></script>

<script src="{% static 'assets/js/price-range-ui.js' %}"></script>

<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/counter-potnt.js' %}"></script>

<script src="{% static 'assets/js/main.js' %}"></script>
<script>
                    function forceLower(strInput)
                    {
                        strInput.value = strInput.value.toLowerCase();
                    }
                </script>
<style>

        .btn {
          border: none;
          color: white;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 16px;
        }
        
        .enableEthereumButton {
          background-color: #037dd6;
        }
        .sendEthButton {
          background-color: #4CAF50;
        }
        
        </style>
        
        <script src="https://cdn.jsdelivr.net/npm/web3@latest/dist/web3.min.js"></script>
        <script src="https://unpkg.com/web3@latest/dist/web3.min.js"></script>
        <script src="{% static 'js/index.js' %}"></script>
</body>


</html>

main/templates/main/manage.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}


<div class="auction-details-area mt-100">
<div class="container">
<div class="row">
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
<div class="auction-details-img-wrap">
<div class="auction-details-img-coming-soon">
<div class="countdown-timer style-three">
<ul data-countdown="2023-02-16">
<li>{{ domain.name }}</li>
</ul>
</div>
</div>
<div class="auction-details-img">
    <p  style="display:flex; align-items:center; justify-content:center; margin-top: 20px;">
{{ domain.image|safe }}
</p>
</div>
</div>
</div>
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12 both-small-50">
<div class="auction-details-content ps-lg-3 ps-0">
<div class="auction-details-content-list">
<ul>
<li><div>Taken By <span>:</span></div> <span>{{ domain.address|truncatechars:15 }}</span></li>
<li><div>Price <span>:</span></div> <span>{{ domain.price }} Core</span></li>
<li><div>Years of Ownership <span>:</span></div> <span>{{ domain.age }} Year(s)</span></li>
<li><div>Expiry Date <span>:</span></div> <span>{{ domain.end_year }}</span></li>
</ul>
</div>
<div class="auction-details-btn-wrap mt-50">
<a class="common-btn design-5" href="{% url 'main:transfer2' domain.token_id domain.name %}">Transfer Name</a>
</div>
</div>
</div>
</div>

<hr>
<div class="row mt-50">
    My domain names:
</div>
<div class="row mt-50">

    {% for item in others %}
<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12">
<div class="single-author-box">
<div class="author-img-wrap w-100" >
<div  style="display:flex; align-items:center; justify-content:center; margin-top: 20px">
{{ item.image|safe }}
</div>
    


</div>
<div class="author-content">
<div class="author-name">
<ul>
<p style="text-align:center; color: #ffae01; font-size: 10px; overflow:hidden; margin-top: 15px; object-fit:contain"> {{ item.address }}</p>
</ul>
</div>
<div class="author-follow-btn text-center">
<a class="common-btn design-1" href="{% url 'main:manage' item.name %}">manage</a>
</div>
</div>
 </div>
</div>

{% endfor %}

</div>

</div>
</div>


<br>


{% endblock %}

main/templates/main/registered.html
{% extends 'main/base3.html' %}
{% load static %}
{% block content %}


<div class="author-area mt-100">
<div class="container">
    
    
<div class="subscribe-area pb-100">
<div class="row justify-content-center">
<div class="col-xl-8 col-lg-10 col-md-12 col-sm-12 col-12">
<div class="subscribe-content text-center">
    <form action="" class="subscribe-form mt-50 wow animate flipInX" data-wow-delay="200ms" data-wow-duration="1500ms" method="post">
	{% csrf_token %}
<input type="text" onkeyup="return forceLower(this);" name="address" placeholder="Enter your wallet address">
<button type="submit">Go</button>
</form>
</div></div></div></div>

<div class="row mt-50">

    {% for item in result %}
<div class="col-xl-3 col-lg-4 col-md-6 col-sm-12 col-12">
<div class="single-author-box">
<div class="author-img-wrap w-100" >
<div  style="display:flex; align-items:center; justify-content:center; margin-top: 20px">
{{ item.image|safe }}
</div>
    


</div>
<div class="author-content">
<div class="author-name">
<ul>
<p style="text-align:center; color: #ffae01; font-size: 10px; overflow:hidden; margin-top: 15px; object-fit:contain"> {{ item.address }}</p>
</ul>
</div>
<div class="author-follow-btn text-center">
<a class="common-btn design-1" href="{% url 'main:manage' item.name %}">manage</a>
</div>
</div>
 </div>
</div>

{% endfor %}

</div>
</div>
</div>
<br><br><br><br>


{% endblock %}